apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: Jaeger
  namespace: argocd
spec:
  strategy: production
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true                                 # turn the cron job deployment on and off
      numberOfDays: 7                               # number of days to wait before deleting a record
      schedule: "55 23 * * *"                       # cron expression for it to
    elasticsearch:
      nodeCount: 1 # Number of Elasticsearch nodes. For high availability use at least 3 nodes. Do not use 2 nodes as 'split brain' problem can happen.
      storage: # <2>
        storageClassName: gp2 # longhorn
        size: 2Gi
      resources: # <3>
        requests:
          cpu: 200m
          memory: 2Gi
        limits:
          memory: 2Gi
      redundancyPolicy: ZeroRedundancy # <4>