apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaegertracing/jaeger-operator.git
    targetRevision: main  # or a specific version/tag
    path: deploy  # this should be the directory containing operator's manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true